2015-09-24 16:38:51,289 ERROR: Exception on /hdd_classify [GET] [in /Library/Python/2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 113, in upload_and_classify
    image_file = req.files['file']
NameError: global name 'req' is not defined
2015-09-24 16:39:53,628 ERROR: Exception on /hdd_classify [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 113, in upload_and_classify
    image_file = req.files['file']
NameError: global name 'req' is not defined
2015-09-24 16:40:40,161 ERROR: Exception on /hdd_classify [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 113, in upload_and_classify
    image_file = request.files['file']
NameError: global name 'req' is not defined
2015-09-24 16:44:08,317 ERROR:   File "server.py", line 114, in upload_and_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:122]
2015-09-24 16:45:00,059 ERROR:   File "server.py", line 114, in upload_and_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:122]
2015-09-24 16:46:43,568 ERROR:   File "server.py", line 114, in upload_and_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:123]
2015-09-24 16:47:21,366 ERROR:   File "server.py", line 114, in upload_and_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:123]
2015-09-24 16:47:21,367 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:52:11,301 ERROR:   File "server.py", line 114, in upload_and_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:123]
2015-09-24 16:52:11,302 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:53:03,268 ERROR:   File "server.py", line 115, in upload_and_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:124]
2015-09-24 16:53:03,268 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:54:20,173 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:54:20,174 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:20,559 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:20,560 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:21,596 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:21,596 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:22,142 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:22,143 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:22,338 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:22,339 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:22,446 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:22,446 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:22,601 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:22,601 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:22,737 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:22,737 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:22,869 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:22,869 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:55:39,080 ERROR:   File "server.py", line 117, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:124]
2015-09-24 16:55:39,087 ERROR: ImmutableMultiDict([]) [in server.py:125]
2015-09-24 16:57:11,894 ERROR:   File "server.py", line 115, in upload_and_classify
    print request.files, request.form, request.args, request.methods
   File "/Library/Python/2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
 [in server.py:123]
2015-09-24 16:57:11,894 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:57:17,113 ERROR:   File "server.py", line 115, in upload_and_classify
    print request.files, request.form, request.args, request.methods
   File "/Library/Python/2.7/site-packages/werkzeug/local.py", line 338, in __getattr__
    return getattr(self._get_current_object(), name)
 [in server.py:123]
2015-09-24 16:57:17,113 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:57:44,950 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 16:57:44,951 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:59:13,195 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 16:59:13,201 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:59:14,013 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 16:59:14,013 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:59:20,165 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 16:59:20,165 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 16:59:21,674 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 16:59:21,675 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:00:35,952 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:00:35,952 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:00:37,023 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:00:37,023 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:00:37,688 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:00:37,689 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:00:52,750 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:00:52,756 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:04:50,059 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:04:50,059 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:07:05,174 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:07:05,174 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:07:11,535 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:07:11,535 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:07:12,728 ERROR:   File "server.py", line 116, in upload_and_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:07:12,728 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:17:32,620 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:17:32,621 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:17:40,578 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:17:40,578 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:17:41,403 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:17:41,403 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:17:42,214 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:17:42,219 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:17:42,800 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:17:42,800 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:17:43,326 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:17:43,326 ERROR: ImmutableMultiDict([]) [in server.py:124]
2015-09-24 17:20:17,125 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
 [in server.py:123]
2015-09-24 17:20:17,125 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:124]
2015-09-24 17:21:11,376 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2617, in __getattr__
    return getattr(self.stream, name)
 [in server.py:123]
2015-09-24 17:21:11,376 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:124]
2015-09-24 17:22:08,924 ERROR:   File "server.py", line 116, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2617, in __getattr__
    return getattr(self.stream, name)
 [in server.py:123]
2015-09-24 17:22:08,924 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:124]
2015-09-24 17:23:06,415 ERROR:   File "server.py", line 115, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2617, in __getattr__
    return getattr(self.stream, name)
 [in server.py:122]
2015-09-24 17:23:06,415 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:123]
2015-09-24 17:23:20,586 ERROR:   File "server.py", line 113, in hdd_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:122]
2015-09-24 17:23:20,586 ERROR: ImmutableMultiDict([]) [in server.py:123]
2015-09-24 17:23:32,208 ERROR:   File "server.py", line 115, in hdd_classify
    if image_file.rsplit ('.', 1)[1] in ALLOWED_EXTENSIONS and '.' in image_file:
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2617, in __getattr__
    return getattr(self.stream, name)
 [in server.py:122]
2015-09-24 17:23:32,208 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:123]
2015-09-24 17:24:38,518 ERROR:   File "server.py", line 116, in hdd_classify
    sec_fname = secure_filename (image_file_name)
 [in server.py:122]
2015-09-24 17:24:38,518 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:123]
2015-09-24 17:25:18,328 ERROR:   File "server.py", line 116, in hdd_classify
    image_file.save (os.path.join (app.config['UPLOAD_FOLDER'], sec_fname))
 [in server.py:121]
2015-09-24 17:25:18,329 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:122]
2015-09-24 17:27:03,839 ERROR:   File "server.py", line 116, in hdd_classify
    image_file.file.save (os.path.join (app.config['UPLOAD_FOLDER'], sec_fname))
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2617, in __getattr__
    return getattr(self.stream, name)
 [in server.py:121]
2015-09-24 17:27:03,839 ERROR: ImmutableMultiDict([('file', <FileStorage: u'hdd2.jpg' ('image/jpeg')>)]) [in server.py:122]
2015-09-24 17:27:58,552 ERROR: Exception on /hdd_classify [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 116, in hdd_classify
    image_file.file.save (os.path.join (app.config['UPLOAD_FOLDER'], sec_fname))
  File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2617, in __getattr__
    return getattr(self.stream, name)
AttributeError: 'file' object has no attribute 'file'
2015-09-24 17:28:26,273 ERROR: Exception on /hdd_classify [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 116, in hdd_classify
    image_file.save (os.path.join (app.config['UPLOAD_FOLDER'], sec_fname))
NameError: global name 'os' is not defined
2015-09-24 17:28:48,645 ERROR: Exception on /hdd_classify [POST] [in /Library/Python/2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 116, in hdd_classify
    image_file.save (os.path.join (app.config['UPLOAD_FOLDER'], sec_fname))
  File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 2597, in save
    dst = open(dst, 'wb')
IOError: [Errno 2] No such file or directory: '/Users/bski/Dev/tmp/hdd2.jpg'
2015-09-24 20:36:14,899 ERROR:   File "server.py", line 116, in hdd_classify
    for x in top_k_idx.tolist():
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:125]
2015-09-24 20:36:55,748 ERROR:   File "server.py", line 138, in hdd_classify
    image_file = request.files['file']
   File "/Library/Python/2.7/site-packages/werkzeug/datastructures.py", line 393, in __getitem__
    raise exceptions.BadRequestKeyError(key)
 [in server.py:148]
